### ISSUE TITLE
work with /usr/share/man directly?

### ISSUE THREAD

**Issue by laoshaw** [Yanpas/mandocset#4]
this script works well with downloaded manpages, I tried to run it against /usr/share/man but the generate docset can not be displayed in zeal, it will be nice to generate docset directly from /usr/share/man

**Comment by laoshaw** [comment]
to answer my own question, i had to gunzip all the gz files then generate the docset and it works

**Comment by Yanpas** [comment]
I'll take a look in nearest future. If you have python skills you can edit `toHtml` function. Either run gzip process and join their output and input, or use Popen.communicate and gzip module

**Comment by laoshaw** [comment]
I know some python, the trick is about those symlinks under /usr/share/man that does not exist under the manpage original releases, otherwise it could be an easy fix.

say: a.gz -> b.gz, we need something eventually like a.html->b.html, at filesystem level it is easy, but sqlite3 needs to record that as well.

**Comment by Yanpas** [comment]
Fixed in master, try it out and reopen if you had any problems

**Comment by laoshaw** [comment]
Just tested it. zeal loads the docset but can actually search it but can not show any content for any API.when zeal is launched it says "Cannot determine index file for docset ManPages", ManPages is the docset name.

**Comment by Yanpas** [comment]
My bad, fixed in master
