### ISSUE TITLE
Automatically fetch Man pages directories

### ISSUE THREAD

**Issue by moritzz** [Yanpas/mandocset#5]
Hi Yan

Thanks a lot for your work.

I'm not a Pyhton guy, so I can't code this myself. Would be great though if you could render the `-p /man/page/dir [/additional/man/page/dir]`optional and instead use the output of `man -w` as source scanning man page directories.

 Yours,  
M. Zimmer

**Comment by Yanpas** [comment]
Hi!

`manpath` seems to be most correct in listing man pages paths. I'm using arch and some of paths in those list are symlinks to other paths in this list. I want to keep this script simple and thus flexible, you can use bash! Here is the answer to your question:
```bash
python mandocset.py -p $(manpath | tr : '\n' | xargs readlink -f | sort | uniq) -o linux
```
[Explanation](https://explainshell.com/explain?cmd=manpath+%7C+tr+%3A+%27%5Cn%27+%7C+xargs+readlink+-f+%7C+sort+%7C+uniq)

**Comment by moritzz** [comment]
Wow, thanks @Yanpas. Apparently I'm not a bash hero too... 🙂

**Comment by moritzz** [comment]
One more thing; I don't know if its due to `brew` not fully ported to Big Sur yet, but there seams to be some issues with `man2html` there. I will now try using `pandoc` instead. Should I keep you posted on Big Sur/man2html issues I encounter in the future?

**Comment by Yanpas** [comment]
Well, leave the comment here, maybe someone will find it useful.

Thanks in advance
